name: clean_flutter_app
description: Enquetes para programadores.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  mockito: ^5.0.15
  faker: ^2.0.0

flutter:
  uses-material-design: true